apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nextjs-blog
  template:
    metadata:
      labels:
        app: nextjs-blog
    spec:
      containers:
      - name: nextjs-blog
        image: ghcr.io/<your-username>/<repo>:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
